version: "3.9"

services:
    database:
        image: postgres
        container_name: api_test
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=incycle
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=api_test
        volumes:
            - pgdata:/data/postgres

    app:
        build: .
        container_name: mongo-connection
        restart: always
        ports:
            - 3335:3335
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
        env_file:
            - ./.env        
volumes:
    pgdata:
        driver: local
