version: "3.9"

services:
    app:
        build: .
        container_name: ca-post
        restart: always
        ports:
            - 3336:3336
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            - database
        env_file:
            - ./.env        
volumes:
    pgdata:
        driver: local
